ApartmentsRentalManagement1/Controllers/RentContractsController.cs
using System;
using System.Net;
using System.Data;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Collections.Generic;
using ApartmentsRentalManagement1.Models;

namespace ApartmentsRentalManagement1.Controllers
{
    public class RentContractsController : Controller
    {
        BusinessObjects objects = new BusinessObjects();

        // GET: RentContracts
        public ActionResult Index()
        {
            return View(objects.GetRentContracts());
        }

        // GET: RentContracts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RentContract contract = objects.FindRentContract(id);

            if (contract == null)
            {
                return HttpNotFound();
            }

            return View(contract);
        }

        // GET: RentContracts/Create
        public ActionResult Create()
        {
            List<SelectListItem> maritals = new List<SelectListItem>
            {
                new SelectListItem() { Text = "Unknown",   Value = "Unknown"   },
                new SelectListItem() { Text = "Single",    Value = "Single"    },
                new SelectListItem() { Text = "Widdow",    Value = "Widdow"    },
                new SelectListItem() { Text = "Married",   Value = "Married"   },
                new SelectListItem() { Text = "Divorced",  Value = "Divorced"  },
                new SelectListItem() { Text = "Separated", Value = "Separated" }
            };

            ViewBag.MaritalStatus = maritals;

            ViewBag.ApartmentID = new SelectList(objects.GetApartments(), "ApartmentID", "Residence");
            ViewBag.EmployeeID = new SelectList(objects.GetEmployees(), "EmployeeID", "Identification");

            return View();
        }

        // POST: RentContracts/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                using (SqlConnection scApartmentsManagement = new SqlConnection(System.
                                                                                Configuration.
                                                                                ConfigurationManager.
                                                                                ConnectionStrings["csApartmentsRentalManagement"].
                                                                                ConnectionString))
                {
                    // This command is used to create a rental contract.
                    SqlCommand cmdRentContracts = new SqlCommand("INSERT INTO Management.RentContracts(ContractNumber, EmployeeID, " +
                                                                 "                                     ContractDate, FirstName, " +
                                                                 "                                     LastName, MaritalStatus, " +
                                                                 "                                     NumberOfChildren, ApartmentID, " +
                                                                 "                                     RentStartDate) " +
                                                                 "VALUES(" + collection["ContractNumber"] + ", " +
                                                                 collection["EmployeeID"] + ", N'" + collection["ContractDate"] +
                                                                 "', N'" + collection["FirstName"] + "', N'" + collection["LastName"] +
                                                                 "', N'" + collection["MaritalStatus"] + "', " +
                                                                 collection["NumberOfChildren"] + ", " + collection["ApartmentID"] +
                                                                 ", N'" + collection["RentStartDate"] + "');",
                                                                 scApartmentsManagement);

                    scApartmentsManagement.Open();
                    cmdRentContracts.ExecuteNonQuery();
                }

                /* When an apartment has been selected for a rental contract, 
                 * we must change the status of that apartment from Available to Occupied. */
                using (SqlConnection scRentManagement = new SqlConnection(System.Configuration.
                                                                                ConfigurationManager.
                                                                                ConnectionStrings["csApartmentsRentalManagement"].
                                                                                ConnectionString))
                {
                    SqlCommand cmdApartments = new SqlCommand("UPDATE Management.Apartments " +
                                                              "SET   OccupancyStatus = N'Occupied'  " +
                                                              "WHERE ApartmentID     =   " + collection["ApartmentID"] + ";",
                                                             scRentManagement);

                    scRentManagement.Open();
                    cmdApartments.ExecuteNonQuery();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RentContracts/Edit/5
        public ActionResult Edit(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RentContract contract = objects.FindRentContract(id);

            if (contract == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> maritals = new List<SelectListItem>
            {
                new SelectListItem() { Text = "Single",    Value = "Single",    Selected = (contract.MaritalStatus == "Single")    },
                new SelectListItem() { Text = "Widdow",    Value = "Widdow",    Selected = (contract.MaritalStatus == "Widdow")    },
                new SelectListItem() { Text = "Married",   Value = "Married",   Selected = (contract.MaritalStatus == "Married")   },
                new SelectListItem() { Text = "Unknown",   Value = "Unknown",   Selected = (contract.MaritalStatus == "Unknown")   },
                new SelectListItem() { Text = "Divorced",  Value = "Divorced",  Selected = (contract.MaritalStatus == "Divorced")  },
                new SelectListItem() { Text = "Separated", Value = "Separated", Selected = (contract.MaritalStatus == "Separated") }
            };

            ViewBag.MaritalStatus = maritals;

            ViewBag.EmployeeID = new SelectList(objects.GetEmployees(), "EmployeeID", "Identification", contract.EmployeeID);
            ViewBag.ApartmentID = new SelectList(objects.GetApartments(), "ApartmentID", "Residence", contract.ApartmentID);

            return View();
        }

        // POST: RentContracts/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    using (SqlConnection scApartmentsManagement = new SqlConnection(System.
                                                                                    Configuration.
                                                                                    ConfigurationManager.
                                                                                    ConnectionStrings["csApartmentsRentalManagement"].
                                                                                    ConnectionString))
                    {
                        string strUpdate = "UPDATE Management.RentContracts " +
                                           "SET   ContractNumber     =   " + collection["ContractNumber"] + ", " +
                                           "      EmployeeID         =   " + collection["EmployeeID"] + ", " +
                                           "      FirstName          = N'" + collection["FirstName"] + "', " +
                                           "      LastName           = N'" + collection["LastName"] + "', " +
                                           "      MaritalStatus      = N'" + collection["MaritalStatus"] + "', " +
                                           "      NumberOfChildren   =   " + collection["NumberOfChildren"] + ", " +
                                           "      ApartmentID        =   " + collection["ApartmentID"] + " " +
                                           "WHERE RentContractID = " + id + ";";
                        if (DateTime.Parse(collection["ContractDate"]) != new DateTime(1900, 1, 1))
                            strUpdate += "UPDATE Management.RentContracts " +
                                         "SET   ContractDate       = N'" + collection["ContractDate"] + "' " +
                                         "WHERE RentContractID = " + id + ";";
                        if (DateTime.Parse(collection["RentStartDate"]) != new DateTime(1900, 1, 1))
                            strUpdate += "UPDATE Management.RentContracts " +
                                         "SET   RentStartDate       = N'" + collection["RentStartDate"] + "' " +
                                         "WHERE RentContractID = " + id + ";";


ApartmentsRentalManagement1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apartment Rental Management :: @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="top-banner"></div>

    <div class="navbar navbar-inverse navbar-top-fixed">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("LEASE APPLICATION", "Index", "Home")</li>
                    <li>@Html.ActionLink("COMMUNITY", "Index", "Home")</li>
                    <li>@Html.ActionLink("FLOOR PLANS", "Index", "Home")</li>
                    <li>@Html.ActionLink("CAREERS", "Index", "Home")</li>
                    <li>@Html.ActionLink("RENT MANAGEMENT", "Index", "RentContracts")</li>
                    <li>@Html.ActionLink("ABOUT ARM", "About", "Home")</li>
                    <li>@Html.ActionLink("CONTACT US", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center common-font blue">&copy; @DateTime.Now.Year - Apartment Rental Management</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ApartmentsRentalManagement1/Views/Shared/_Management.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apartment Rental Management :: @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Apartment Rental Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Apartments", "Index", "Apartments")</li>
                    <li>@Html.ActionLink("Rent Contracts", "Index", "RentContracts")</li>
                    <li>@Html.ActionLink("Payments", "Index", "Payments")</li>
                    <li>@Html.ActionLink("About ARM", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center common-font blue">&copy; @DateTime.Now.Year - Apartment Rental Management</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>